export const primeVueRussianLocale = {
  clear: 'Очистить',
  apply: 'Применить',
  accept: 'Да',
  reject: 'Нет',
  choose: 'Выбрать',
  upload: 'Загрузить',
  cancel: 'Отмена',
  completed: 'Завершено',
  pending: 'Ожидает',
  dayNames: [
    'Воскресенье',
    'Понедельник',
    'Вторник',
    'Среда',
    'Четверг',
    'Пятница',
    'Суббота',
  ],
  dayNamesShort: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  monthNames: [
    'Январь',
    'Февраль',
    'Март',
    'Апрель',
    'Май',
    'Июнь',
    'Июль',
    'Август',
    'Сентябрь',
    'Октябрь',
    'Ноябрь',
    'Декабрь',
  ],
  monthNamesShort: [
    'Янв',
    'Фев',
    'Мар',
    'Апр',
    'Май',
    'Июн',
    'Июл',
    'Авг',
    'Сен',
    'Окт',
    'Ноя',
    'Дек',
  ],
  chooseYear: 'Выбрать год',
  chooseMonth: 'Выбрать месяц',
  chooseDate: 'Выбрать дату',
  prevDecade: 'Предыдущее десятилетие',
  nextDecade: 'Следующее десятилетие',
  prevYear: 'Предыдущий год',
  nextYear: 'Следующий год',
  prevMonth: 'Предыдущий месяц',
  nextMonth: 'Следующий месяц',
  today: 'Сегодня',
  firstDayOfWeek: 1,
  dateFormat: 'dd.mm.yy',
  passwordPrompt: 'Введите пароль',
  emptyFilterMessage: 'Ничего не найдено',
  emptySearchMessage: 'Ничего не найдено',
  emptyMessage: 'Нет доступных вариантов',
  searchMessage: 'Найдено вариантов: {0}',
  selectionMessage: 'Выбрано вариантов: {0}',
  emptySelectionMessage: 'Ничего не выбрано',
  aria: {
    trueLabel: 'Да',
    falseLabel: 'Нет',
    nullLabel: 'Не выбрано',
    selectAll: 'Выбрать всё',
    unselectAll: 'Снять выбор со всех',
    close: 'Закрыть',
    previous: 'Назад',
    next: 'Вперёд',
    navigation: 'Навигация',
    scrollTop: 'Наверх',
    moveTop: 'Переместить в начало',
    moveUp: 'Переместить выше',
    moveDown: 'Переместить ниже',
    moveBottom: 'Переместить в конец',
    pageLabel: 'Страница {page}',
    firstPageLabel: 'Первая страница',
    lastPageLabel: 'Последняя страница',
    nextPageLabel: 'Следующая страница',
    prevPageLabel: 'Предыдущая страница',
    rowsPerPageLabel: 'Строк на странице',
    showFilterMenu: 'Показать фильтры',
    hideFilterMenu: 'Скрыть фильтры',
    listLabel: 'Список вариантов',
  },
}
