export const PLATFORM_PERMISSION_CODES = [
  "platform.projects.read",
  "platform.projects.create",
  "platform.projects.update",
  "platform.projects.archive",
  "platform.cms_users.read",
  "platform.cms_users.create",
  "platform.cms_users.update",
  "platform.cms_users.deactivate",
  "platform.cms_users.reactivate",
  "platform.cms_users.reset_credentials",
  "platform.memberships.read",
  "platform.memberships.manage",
  "platform.roles.read",
  "platform.roles.manage",
  "platform.audit.read",
  "platform.ai_pricing.read",
  "platform.ai_pricing.write",
  "platform.translation_usage.read",
  "platform.notifications.operations.read",
  "platform.notifications.operations.operate",
] as const;

export const PROJECT_PERMISSION_CODES = [
  "project.settings.read",
  "project.settings.write",
  "project.credentials.rotate",
  "project.members.read",
  "project.members.manage",
  "project.roles.read",
  "project.roles.manage",
  "project.end_users.read",
  "project.end_users.write",
  "project.profiles.read",
  "project.profile_contract.read",
  "project.profile_contract.write",
  "project.profile_contract.publish",
  "project.conversations.read",
  "project.conversations.reply",
  "project.conversations.ai_suspend",
  "project.cms_agent.use",
  "project.ai_analyses.read",
  "project.ai_analyses.run",
  "project.ai_analyses.schedule",
  "project.ai_analyses.manage",
  "project.ai_analysis_cost.read",
  "project.ai_operations.read",
  "project.ai_operations.sensitive.read",
  "project.ai_operations.subjects.read",
  "project.ai_operations.audit.read",
  "project.ai_costs.read",
  "project.ai_allowance.accrual_rules.read",
  "project.ai_allowance.accrual_rules.manage",
  "project.ai_allowance.accrual_receipts.read",
  "project.end_user_state.sensitive.read",
  "project.end_user_state.manage",
  "project.ai_allowance.read",
  "project.ai_allowance.manage",
  "project.ai_allowance.grant",
  "project.ai_allowance.reconcile",
  "project.cases.read",
  "project.cases.manage",
  "project.cases.assign",
  "project.cases.escalate",
  "project.cases.analytics.read",
  "project.cases.settings.manage",
  "project.end_user_cases.verify",
  "project.event_query_policy.manage",
  "project.event_query_policy.preview",
  "project.user_memory.read",
  "project.user_memory.manage",
  "project.ai_review.read",
  "project.ai_review.run",
  "project.scenarios.read",
  "project.scenarios.write",
  "project.scenarios.publish",
  "project.scenarios.classify_security",
  "project.segments.read",
  "project.segments.write",
  "project.event_catalog.read",
  "project.event_catalog.write",
  "project.event_catalog.publish",
  "project.event_logs.read",
  "project.scenario_runs.read",
  "project.knowledge.read",
  "project.knowledge.write",
  "project.actions.read",
  "project.actions.manage",
  "project.actions.manage_ai_exposure",
  "project.ui_registry.read",
  "project.ui_registry.write",
  "project.translation.create",
  "project.translation.read",
  "project.translation.cancel",
  "project.conversations.reply_without_translation",
  "project.support.assignments.self_manage",
  "project.support.assignments.override",
  "project.support.assignments.force_assign",
  "project.support.routing.read",
  "project.support.routing.manage",
  "project.support.routing.receive",
  "project.support.sla.read",
  "project.support.sla.correct",
  "project.support.sla.manage",
  "project.support.availability.read",
  "project.support.availability.self_manage",
  "project.support.availability.override",
  "project.support.lead_control.read",
  "project.support.activity.read",
  "project.support.alerts.read",
  "project.support.alerts.manage",
  "project.support.internal_notes.read",
  "project.support.internal_notes.write",
  "project.support.internal_notes.history_read",
  "project.support.internal_notes.redact",
  "project.support.search.read",
  "project.support.saved_views.read",
  "project.support.saved_views.self_manage",
  "project.support.saved_views.manage",
  "project.support.macros.read",
  "project.support.macros.use",
  "project.support.macros.manage",
  "project.support.knowledge.read",
  "project.support.knowledge.manage",
  "project.support.content_retention.manage",
  "project.support.content_legal_hold.manage",
  "project.support.content_rollout.manage",
  "project.ai_usage.read",
  "project.notifications.read",
  "project.notifications.manage",
  "project.integrations.read",
  "project.integrations.manage",
  "project.integration_activity.read",
  "project.integration_api_requests.read",
  "project.integration_message_content.read",
  "project.telegram.links.read",
  "project.telegram.personal_messages.send",
  "project.telegram.broadcasts.read",
  "project.telegram.broadcasts.draft",
  "project.telegram.broadcasts.approve",
  "project.telegram.broadcasts.operate",
  "project.audit.read",
] as const;

export type PlatformPermissionCode = (typeof PLATFORM_PERMISSION_CODES)[number];
export type ProjectPermissionCode = (typeof PROJECT_PERMISSION_CODES)[number];

export const PROJECT_SETTINGS_SURFACE_READ_PERMISSIONS = [
  "project.settings.read",
  "project.profile_contract.read",
  "project.ai_usage.read",
  "project.event_query_policy.manage",
  "project.event_query_policy.preview",
] as const satisfies readonly ProjectPermissionCode[];

export function hasProjectPermission(
  effectivePermissionCodes: readonly string[],
  permission: ProjectPermissionCode,
): boolean {
  return effectivePermissionCodes.includes(permission);
}

export function hasPlatformPermission(
  platformPermissionCodes: readonly string[],
  permission: PlatformPermissionCode,
): boolean {
  return platformPermissionCodes.includes(permission);
}

export function hasProjectOrPlatformPermission(
  platformPermissionCodes: readonly string[],
  effectivePermissionCodes: readonly string[],
  projectPermission: ProjectPermissionCode,
  platformPermission: PlatformPermissionCode,
): boolean {
  return (
    hasProjectPermission(effectivePermissionCodes, projectPermission) ||
    hasPlatformPermission(platformPermissionCodes, platformPermission)
  );
}
